export enum ExcelPageEnum {
  IMPOSTAZIONI = "IMPOSTAZIONI",
  GIOCATORI = "GIOCATORI",
  BRIAN = "BRIAN",
  SIMO = "SIMO",
  PIER = "PIER",
  MICHE = "MICHE",
  MICHI = "MICHI",
  LAZZA = "LAZZA",
  VAVA = "VAVA",
  PIANTA = "PIANTA",
  SUPER = "SUPER",
  TIZI = "TIZI",
}
